export const HOME_SCREEN = "HOME_SCREEN";
export const LOGIN_SCREEN = "LOGIN_SCREEN";
export const REGISTER_SCREEN = "REGISTER_SCREEN";
export const GETTING_STARTED_SCREEN = "GETTING_STARTED_SCREEN";
export const TOP_DONORS_SCREEN = "TOP_DONORS_SCREEN";
export const CHAT_SCREEN = "CHAT_SCREEN";
export const PROFILE_SCREEN = "PROFILE_SCREEN";
export const HOME_TABS = "HOME_TABS";
